---
abstract: 'test-time utilities for checking C headers, libraries, or OS features'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-CChecker
requires:
  Capture::Tiny: 0
  ExtUtils::CChecker: 0.09
  Test::Builder::Module: 0
  base: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/plicease/test-cchecker/issues
  homepage: http://perl.wdlabs.com/Test-CChecker/
  repository: git://github.com/plicease/test-cchecker.git
version: 0.04
